---
- name: "[k8s] {{ action }} ConfigMap {{ kafka_cluster_name }}-custom-zookeeper-config"
  k8s:
    host: "{{ ocp }}"
    api_key: "{{ ocp_token }}"
    verify_ssl: no
    namespace: "{{ kafka-namespace }}"
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ kafka_cluster_name }}-custom-zookeeper-config"
        namespace: "{{ kafka-namespace }}"
      data:
        log4j.properties: "{{ lookup('file', 'zookeeper-configmap/log4j.properties') }}"

- name: "[k8s] {{ action }} ConfigMap {{ kafka_cluster_name }}-custom-kafka-config"
  k8s:
    host: "{{ ocp }}"
    api_key: "{{ ocp_token }}"
    verify_ssl: no
    namespace: "{{ kafka-namespace }}"
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ kafka_cluster_name }}-custom-kafka-config"
        namespace: "{{ kafka-namespace }}"
      data:
        log4j.properties: "{{ lookup('file', 'kafka-configmap/log4j.properties') }}"


- name: "[k8s] {{ action }} Kafka Cluster {{ kafka_cluster_name }}"
  k8s:
    host: "{{ ocp }}"
    api_key: "{{ ocp_token }}"
    verify_ssl: no
    namespace: "{{ kafka-namespace }}"
    state: "{{ state }}"
    definition: "{{ lookup('template', 'kafka-cluster.yaml.j2') }}"

- name: "[command] Assign strimzi-admin role to user"
  command: "oc --token='{{ ocp_token }}' adm policy add-cluster-role-to-user strimzi-admin {{ user }}"
  when: state == "present"
